server:
  port: 7450
spring:
  datasource:
    url: jdbc:mysql://localhost:65511/crud
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 1000
    password: 0z.z6OVHGLwLmLP9wpunu
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000